name: Sleep Tracker
skillMetadata:
  sections:
    - name: Birth Date
      fields:
        - name: year
          type: number
          label: Year
          value: ""
          placeholder: 1993
        - name: month
          type: select
          label: Month
          options: "January|01;February|02;March|03;April|04;May|05;June|06;July|07;August|08;September|09;October|10;November|11;December|12"
          value: 12
        - name: day
          type: number
          label: Day
          value: ""
          placeholder: 16
        - name: attach_to_naptime
          type: checkbox
          label: Attach to Naptime skill
          value: "false"
