name: Sleep Tracker
skillMetadata:
  sections:
    - name: Birth Date
      fields:
        - name: year
          type: Number
          label: Year
          value: ""
          placeholder: 1993
          name: month
          type: Number
          label: Month
          value: ""
          placeholder: 12
          name: day
          type: Number
          label: Day
          value: ""
          placeholder: 16
